// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcxutbgeqzxwxkjqdhpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjeHV0YmdlcXp4d3hranFkaHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTQ1NzEsImV4cCI6MjA3MzMzMDU3MX0.NScsK2gKyvRg2hfDd5vHRukgoKrBB86ZV8dSd_-P6ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});